spring:
  application:
    name: CianApplication
  jta:
    enabled: true
    transaction-manager-id: app-tm
    atomikos:
      properties:
        log-base-dir: ./atomikos-txlog
        max-timeout: 600000
  datasource:
    initialize: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta.persistence.transactionType: JTA
      hibernate.transaction.coordinator_class: jta
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.AtomikosJtaPlatform
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  quartz:
    auto-startup: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: onishkovvalera@gmail.com
    password: ifpyupsnetmbfyii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true




server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
        scheduling:
          quartz: DEBUG
      quartz:
        core:
          QuartzScheduler: DEBUG
