-- liquibase formatted sql

-- changeset onish:1757322265274-1
CREATE TABLE address
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country          VARCHAR(255),
    city             VARCHAR(255),
    street           VARCHAR(255),
    house_number     VARCHAR(255),
    apartment_number VARCHAR(255),
    postal_code      VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);

-- changeset onish:1757322265274-2
CREATE TABLE advertisement
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email                    VARCHAR(255),
    paid_promotional         BOOLEAN,
    advertisement_status     SMALLINT,
    price                    DOUBLE PRECISION                        NOT NULL,
    time                     TIMESTAMP WITHOUT TIME ZONE,
    address_id               BIGINT,
    apartment_description_id BIGINT,
    user_id                  BIGINT,
    CONSTRAINT pk_advertisement PRIMARY KEY (id)
);

-- changeset onish:1757322265274-3
CREATE TABLE apartment_description
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_of_rooms  INTEGER,
    area             DOUBLE PRECISION                        NOT NULL,
    type             SMALLINT,
    floor            INTEGER                                 NOT NULL,
    total_floors     INTEGER,
    has_balcony      BOOLEAN,
    description_text VARCHAR(255),
    CONSTRAINT pk_apartment_description PRIMARY KEY (id)
);

-- changeset onish:1757322265274-4
CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    surname      VARCHAR(255),
    email        VARCHAR(255),
    password     VARCHAR(255),
    phone_number VARCHAR(255),
    role         SMALLINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset onish:1757322265274-5
ALTER TABLE advertisement
    ADD CONSTRAINT FK_ADVERTISEMENT_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

-- changeset onish:1757322265274-6
ALTER TABLE advertisement
    ADD CONSTRAINT FK_ADVERTISEMENT_ON_APARTMENTDESCRIPTION FOREIGN KEY (apartment_description_id) REFERENCES apartment_description (id);

-- changeset onish:1757322265274-7
ALTER TABLE advertisement
    ADD CONSTRAINT FK_ADVERTISEMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

